# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: 2.6

steps:
- checkout: self
  persistCredentials: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#- task: VsixToolsUpdateVersion@2
#  displayName: 'Update Vsix Version'
#  inputs:
#    FileName: $(Build.SourcesDirectory)\$(system.teamProject)\source.extension.vsixmanifest
#    VersionNumber: '$(Build.BuildNumber)'
  
# Build VS2019 extension
- task: VSBuild@1
  displayName: 'VS2019 Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    customVersion: '16.0'
    
# Build VS2022 extension
- task: VSBuild@1
  displayName: 'VS2022 Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    customVersion: '17.0'

- task: CopyFiles@2
  displayName: 'Copy Artifacts to Staging'
  inputs: 
    contents: '**\?(*.vsix|extension-manifest.json|README.md)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(system.teamProject)'
